#!/usr/bin/env bash

USER=${USER:-carlos}
HOME=${HOME:-/home/$USER}

# ░█░█░█▄█░░░▀█▀░█▀█░█▀▄░█▀▀░█▀█░█▀▀░█▀█░█▀▄░█▀▀░█▀█░▀█▀░░░█░█░█▀█░▀█▀░█░█░█▀▀░█░█░█▀▀
# ░█▄█░█░█░░░░█░░█░█░█░█░█▀▀░█▀▀░█▀▀░█░█░█░█░█▀▀░█░█░░█░░░░█▀█░█░█░░█░░█▀▄░█▀▀░░█░░▀▀█
# ░▀░▀░▀░▀░░░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░░░▀▀▀░▀░▀░▀▀░░▀▀▀░▀░▀░░▀░░░░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░░▀░░▀▀▀

# terminal emulator
super + Return
	kitty

# program launcher
super + @space
	rofi -combi-modi window,drun,run,ssh -lines 15 -location 0 -show combi -run-shell-command 'kitty -e bash -ic "{cmd} && read"'

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# ░█▀▄░█▀▀░█▀█░█░█░█▄█░░░█░█░█▀█░▀█▀░█░█░█▀▀░█░█░█▀▀
# ░█▀▄░▀▀█░█▀▀░█▄█░█░█░░░█▀█░█░█░░█░░█▀▄░█▀▀░░█░░▀▀█
# ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀░░░▀░▀░▀▀▀░░▀░░▀░▀░▀▀▀░░▀░░▀▀▀

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

# ░█▀█░█▀█░█▀█░█░░░▀█▀░█▀▀░█▀█░▀█▀░▀█▀░█▀█░█▀█░█▀▀
# ░█▀█░█▀▀░█▀▀░█░░░░█░░█░░░█▀█░░█░░░█░░█░█░█░█░▀▀█
# ░▀░▀░▀░░░▀░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀

# Screenshot (fullscreen)
Print
	scrot '/home/carlos/Imagens/captures/%Y-%m-%d_$wx$h.png' -e 'xclip -selection clipboard -t image/png $f'

# Screenshot (selection)
alt + Print
	flameshot gui -p '/home/carlos/Imagens/captures/'
	#scrot -s '/home/carlos/Imagens/captures/%Y-%m-%d_$wx$h.png' -e 'xclip -selection clipboard -t image/png $f'

# Browser padrão
alt + b
	brave-browser

# Thunar (gerenciador de arquivos)
alt + f
	thunar

# Emacs (editor de código)
alt + c
	emacs

# Wireless Network Manager
super + r
	$HOME/.config/rofi/rofi-network-manager/rofi-network-manager.sh

# Brilho da tela
super + {plus,minus}
	$HOME/.local/bin/screen-brightness-lvl {0.1,-0.1}

# Envia conteúdo da área de transferência ao Android como notificação
super + c
	$HOME/.local/bin/notify-android

# Ajuda de teclas de atalho
super + F1
	zenity --info --text="SUPER + ESC\t\t\tReload sxhkdrc\nSUPER + ALT + q\t\tEnd bspwm\nSUPER + ALT + r\t\tReload bspwm\nSUPER + r\t\t\tWireless Network Manager\nSUPER + c\t\t\tNotificação Android\nSUPER + F2\t\t\tKeepassXC\nSUPER + F3\t\t\tTetris\nSUPER + F4\t\t\tMensagem chamativa\nSUPER + F5\t\t\tGera comentário\nSUPER + F6\t\t\tGerenciador de arquivos\nSUPER + F7\t\t\tTerminal\nSUPER + F8\t\t\tCMUS\nSUPER + F9\t\t\tBTM\nSUPER + F10\t\t\tQuicknotes" --title="Shortcuts" --width=400 --height=330

# Copia para o clipboard imagem com mensagem chamativa
super + F4
	$HOME/.local/bin/shoutcbdlg

# Gera cabeçalho para comentários de scripts do shell, Python, Perl, etc...
super + F5
	$HOME/.local/bin/gen-header-comment-dlg


# ░█▀▀░█▀▀░█▀▄░█▀█░▀█▀░█▀▀░█░█░█▀█░█▀█░█▀▄░█▀▀
# ░▀▀█░█░░░█▀▄░█▀█░░█░░█░░░█▀█░█▀▀░█▀█░█░█░▀▀█
# ░▀▀▀░▀▀▀░▀░▀░▀░▀░░▀░░▀▀▀░▀░▀░▀░░░▀░▀░▀▀░░▀▀▀

# KeepassXC
super + F2
	tdrop -a -w 44% -h 68% -y 20% -x 30% keepassxc

# Tetris
super + F3
	tdrop -a -w 44% -h 68% -y 20% -x 30% higan "$HOME/Games/emulators/nes/roms/tetrisgym.nes"
#	tdrop -ma -w 55% -h 60% -y 20% -x 17% gnome-terminal --hide-menubar -e bastet

# File manager
super + F6
	tdrop -ma -w 70% -h 70% -y 20% -x 17% thunar

# Shell
super + F7
	tdrop -ma -w 70% -h 70% -y 20% -x 17% kitty --class=kitty --title=Terminal

# Cmus
super + F8
	tdrop -ma -w 70% -h 70% -y 20% -x 17% gnome-terminal --hide-menubar -e cmus

# BTM
super + F9
	tdrop -ma -w 70% -h 70% -y 20% -x 17% alacritty --class=alacritty --title=btm -e btm

# Quicknotes
super + F10
	tdrop -ma -w 70% -h 70% -y 20% -x 17% ghostwriter "$HOME/Dropbox/obsidian_vaults/principal/03 - Others/Quicknote.md"

# YouTube
super + F11
	tdrop-webapp "https://www.youtube.com"

# Netflix
super + F12
	tdrop-webapp "https://www.netflix.com"

# Udemy
super + Print
	tdrop-webapp "https://www.udemy.com"

# Search selected text on Google
super + alt + F1
	google-selected

# ░█▀▀░▀█▀░█▀█░▀█▀░█▀▀░░░█░█▀▀░█░░░█▀█░█▀▀░█▀▀
# ░▀▀█░░█░░█▀█░░█░░█▀▀░▄▀░░█▀▀░█░░░█▀█░█░█░▀▀█
# ░▀▀▀░░▀░░▀░▀░░▀░░▀▀▀░▀░░░▀░░░▀▀▀░▀░▀░▀▀▀░▀▀▀

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# ░█▀▀░█▀█░█▀▀░█░█░█▀▀░░░█░█▀▀░█░█░█▀█░█▀█
# ░█▀▀░█░█░█░░░█░█░▀▀█░▄▀░░▀▀█░█▄█░█▀█░█▀▀
# ░▀░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░░░▀▀▀░▀░▀░▀░▀░▀░░

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# ░█▀█░█▀▄░█▀▀░█▀▀░█▀▀░█░░░█▀▀░█▀▀░▀█▀
# ░█▀▀░█▀▄░█▀▀░▀▀█░█▀▀░█░░░█▀▀░█░░░░█░
# ░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░░▀░

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# ░█▄█░█▀█░█░█░█▀▀░░░█░█▀▄░█▀▀░█▀▀░▀█▀░▀▀█░█▀▀
# ░█░█░█░█░▀▄▀░█▀▀░▄▀░░█▀▄░█▀▀░▀▀█░░█░░▄▀░░█▀▀
# ░▀░▀░▀▀▀░░▀░░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
