#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
  colorscheme = "dracula"
  colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
  enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = true

[[layers]]
  name = "colorscheme"
  enable = true

[[layers]]
  name = 'shell'
  enable = true
  default_position = 'top'
  default_height = 30

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "checkers"
  enable = true

[[layers]]
  name = "lang#javascript"
  enable = true

[[layers]]
  name = "lang#typescript"
  enable = true

[[layers]]
  name = "lang#java"
  enable = true

[[layers]]
  name = "lang#rust"
  enable = true

[[layers]]
  name = "lang#python"
  enable = true

[[layers]]
  name = "lang#markdown"
  enable = true

[[layers]]
  name = "lsp"
  enable = true
  filetypes = [
      "java",
      "rust",
    ]
    [layers.override_cmd]
        java = [
            "java",
            "-Declipse.application=org.eclipse.jdt.ls.core.id1",
            "-Dosgi.bundles.defaultStartLevel=4",
            "-Declipse.product=org.eclipse.jdt.ls.core.product",
            "-Dlog.protocol=true",
            "-Dlog.level=NONE",
            "-noverify",
            "-Xmx1G",
            "-jar",
            "/home/carlos/.local/share/dev/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar",
            "-configuration",
            "/home/carlos/.local/share/dev/jdt-language-server-latest/config_linux",
            "-data",
            "/home/carlos/.cache/javalsp"
            ]
        rust = ['rls']

[[custom_plugins]]
  name = 'wakatime/vim-wakatime'
  enable = true
  merged = 0

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  enable = true
  merged = 0

[[custom_plugins]]
  repo = "dracula/vim"
  enable = true
  merged = 0

#[options]
#  bootstrap_before = 'myspacevim#before'
#  bootstrap_after = 'myspacevim#after'


